import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products/products.json'
import {useCartContext} from '../hooks/cart'
import Link from 'next/link'

const Home: NextPage = () => {
  // const [cart, setCart] = useState<any>(defaultCart)
  // const {cart, addToCart, subTotal, totalItems, handleBuy} = useCart()
  const {totalItems, subTotal, handleBuy, addToCart, cart} = useCartContext()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org"> E-commerce</a>
        </h1>

        <p className={styles.description}>
          Stripe is a payment platform that enables anyone to collect money from
        </p>
        <div className={styles.checkout}>
          <div>Subtotal: {subTotal}</div>
          <div>Total Items: {totalItems}</div>
          <button
            className={styles.button}
            onClick={() => handleBuy(cart.products)}
          >
            Check Out
          </button>
        </div>

        <ul className={styles.grid}>
          {products.products.map(product => (
            <li className={styles.card} key={product.id}>
              <Link href={`/products/${product.id}`}>
                <Image
                  src={product.thumbnail}
                  alt={product.title}
                  layout="responsive"
                  width={250}
                  height={250}
                  className={styles.cardImage}
                />
              </Link>
              <h2>{product.title}</h2>
              <p>{product.description}</p>
              <button
                className={styles.button}
                // onClick={() => handleBuy(product)}
                onClick={() => addToCart(product)}
              >
                Add To Cart
              </button>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default Home
