import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products/products.json'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org"> E-commerce</a>
        </h1>

        <p className={styles.description}>
          Stripe is a payment platform that enables anyone to collect money from
        </p>

        <ul className={styles.grid}>
          {products.products.map(product => (
            <li className={styles.card} key={product.id}>
              <a href="https://nextjs.org/docs/features/typescript">
                <Image
                  src={product.thumbnail}
                  alt={product.title}
                  layout="responsive"
                  width={250}
                  height={250}
                  className={styles.cardImage}
                />
                <h2>{product.title}</h2>
                <p>{product.description}</p>
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
