import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products/products.json'
import {initiateCheckout} from '../lib/payments'
import {useState} from 'react'

const defaultCart = {
  products: [],
}

const defaultCartInfo = {
  products: {},
}

const Home: NextPage = () => {
  const [cart, setCart] = useState<any>(defaultCart)
  const [cartInfo, setCartInfo] = useState<any>(defaultCartInfo)

  const addToCart = (product: any) => {
    if (cart.products.find((p: any) => p.price === product.id)) {
      const newCart = {...cart}
      newCart.products = newCart.products.map((p: any) => {
        if (p.price === product.id) {
          p.quantity++
        }
        return p
      })
      setCart(newCart)
    } else {
      setCart({
        ...cart,
        products: [
          ...cart.products,
          {price: product.id, quantity: 1, pricePerItem: product.price},
        ],
      })
    }
  }

  const subTotal = cart.products.reduce((acc: number, curr: any) => {
    return acc + curr.pricePerItem * curr.quantity
  }, 0)

  const totalItems = cart.products.reduce((acc: number, curr: any) => {
    return acc + curr.quantity
  }, 0)

  // AddToCartInfo is a function that adds the product to the cartInfo object
  // and then sets the cartInfo object to the new cartInfo object
  // *** This is a temporary solution until we have a real cart ***
  const addToCartInfo = (product: any) => {
    if (cartInfo.products[product.id]) {
      const newCartInfo = {...cartInfo}
      newCartInfo.products[product.id]++
      setCartInfo(newCartInfo)
    } else {
      setCartInfo({
        ...cartInfo,
        products: {...cartInfo.products, [product.id]: 1},
      })
    }
  }

  const handleBuy = (products: any) => {
    initiateCheckout({
      lineItems: products.map((product: any) => ({
        price: product.price,
        quantity: product.quantity,
      })),
    })
  }

  // console.log('cartInfo', cartInfo)
  console.log('subTotal', subTotal)
  console.log('cart', cart)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org"> E-commerce</a>
        </h1>

        <p className={styles.description}>
          Stripe is a payment platform that enables anyone to collect money from
        </p>
        <div className={styles.checkout}>
          <div>Subtotal: {subTotal}</div>
          <div>Total Items: {totalItems}</div>
          <button
            className={styles.button}
            onClick={() => handleBuy(cart.products)}
          >
            Check Out
          </button>
        </div>

        <ul className={styles.grid}>
          {products.products.map(product => (
            <li className={styles.card} key={product.id}>
              <a href="https://nextjs.org/docs/features/typescript">
                <Image
                  src={product.thumbnail}
                  alt={product.title}
                  layout="responsive"
                  width={250}
                  height={250}
                  className={styles.cardImage}
                />
              </a>
              <h2>{product.title}</h2>
              <p>{product.description}</p>
              <button
                className={styles.button}
                // onClick={() => handleBuy(product)}
                onClick={() => addToCart(product)}
              >
                Add To Cart
              </button>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
